"""ver 6.1 altered relationship btw venue and par_venue 

Revision ID: 160a942be60a
Revises: 71ad1239b030
Create Date: 2022-06-03 10:50:54.367251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160a942be60a'
down_revision = '71ad1239b030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Par_venue_venue_fkey', 'Par_venue', type_='foreignkey')
    op.drop_column('Par_venue', 'venue')
    op.add_column('Venue', sa.Column('par_venue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Venue', 'Par_venue', ['par_venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'par_venue_id')
    op.add_column('Par_venue', sa.Column('venue', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Par_venue_venue_fkey', 'Par_venue', 'Venue', ['venue'], ['id'])
    # ### end Alembic commands ###
