"""ver 5 rmove address from artist

Revision ID: 85b503e1d04a
Revises: 9db60f9c9e73
Create Date: 2022-06-03 00:43:12.160320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b503e1d04a'
down_revision = '9db60f9c9e73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
